% A=load('Test_HTS_03.mat');

% names=fieldnames(A);

% CONVERSION OF VARIABLES
% temperatures


calc_values.T_HTS_in=convert_theta2T(input_values.theta_HTS_in);
calc_values.T_CaCO3_in=convert_theta2T(input_values.theta_bed_in);

calc_values.T=calc_T(...
	input_values.theta_bed_in,... 
	input_values.theta_HTS_in...
);

% cp values for T

calc_values.cp_air=calc_cp_air(calc_values.T);
calc_values.cp_CaCO3=calc_cp_CaCO3(calc_values.T);
calc_values.cp_Al2O3=calc_cp_Al2O3(calc_values.T);

% lambda values for T
% load('table_lambda_air.mat');
% load('table_lambda_CaCO3.mat');

calc_values.lambda_air=lookup_lambda_air(calc_values.T, table_lambda_air);
calc_values.lambda_CaCO3=lookup_lambda_CaCO3(calc_values.T, table_lambda_CaCO3);
calc_values.lambda_Al2O3=calc_lambda_Al2O3(calc_values.T);


% lambda_bed, only particles in bed, here CaCO3

calc_values.lambda_bed=calc_heat_conductivity_bed(...
	calc_values.T, ...
	input_values.rho_p_solid, ...
	input_values.rho_p_bed, ...
	input_values.C, ...
	constants.R, ...
	input_values.M, ...
    calc_values.lambda_CaCO3, ...
    calc_values.lambda_air, ...
	input_values.p, ...
    calc_values.cp_air, ...
	input_values.Cf,...
	input_values.f_zeta,...
	input_values.d_p, ...
	constants.sigma,...
	input_values.epsilon_bed,...
	input_values.phi_p...
);


[calc_values.alpha, calc_values.alpha_WS, calc_values.alpha_beddry] =calc_heat_transfer_coefficient_HTS(...
	calc_values.T,              ...
	input_values.C,             ...
	constants.R,                ...
	input_values.M,             ...
	calc_values.lambda_air,      ...
	input_values.p,             ...
	calc_values.cp_air,          ...
	input_values.rho_HTS_bed,   ...
	input_values.rho_HTS_solid, ...
	input_values.d_HTS,         ...
	input_values.d_p,           ...
	constants.sigma,            ...
	input_values.epsilon_HTS,   ...
	input_values.epsilon_bed,   ...
	input_values.delta_p,       ...
	input_values.rho_p_bed,     ...
	calc_values.lambda_bed,     ...
	calc_values.cp_CaCO3,       ...
	input_values.t              ...
);

% Heat Exchanger Parameter (here HTS)

calc_values.A_HTS=calc_A_HTS(input_values.d_HTS);
calc_values.A_HTS_tot=calc_A_HTS_tot(input_values.n_1, calc_values.A_HTS);


% heat flow

calc_values.q_p=calc_q_p_hx_CaCO3(   ...
    calc_values.alpha,      ...
	calc_values.T_HTS_in,   ...
	calc_values.T_CaCO3_in ...
);

calc_values.Q=calc_Q_hx_CaCO3(...
	calc_values.alpha,      ...
	calc_values.T_HTS_in,   ...
	calc_values.T_CaCO3_in, ...
	calc_values.A_HTS_tot,  ...
	input_values.t          ...
);

calc_values.V_HTS_tot=calc_V_tot(input_values.d_HTS, input_values.n_1);
calc_values.m_1=calc_m(input_values.rho_HTS_solid, calc_values.V_HTS_tot);

calc_values.T_HTS_out=calc_T_HTS_out(...
    calc_values.Q, 					... 
    calc_values.T_HTS_in,           ...
    calc_values.cp_Al2O3,           ...
    calc_values.m_1,                ...
    input_values.t                  ...
 );

calc_values.V_CaCO3_tot=calc_V_tot(input_values.d_p, input_values.n_2);
calc_values.m_2=calc_m(input_values.rho_p_solid, calc_values.V_CaCO3_tot);

calc_values.T_CaCO3_out=calc_T_CaCO3_out(...
    calc_values.Q, 					... 
    calc_values.T_CaCO3_in,         ...
    calc_values.cp_CaCO3,           ...
    calc_values.m_2,                ...
    input_values.t                  ...
 );


% critical residence time

calc_values.t_c=calc_t_c(   ...
    input_values.rho_p_bed, ...
    calc_values.lambda_bed, ...
    calc_values.cp_CaCO3,   ...
    calc_values.alpha_WS    ...
);


