function [result] = execute_L_valve(x)

% renaming: parameters for optimization

parameters.w_CaO=x(1);
parameters.w_CaCO3=x(2);
parameters.t_res=x(3); 

% loading material values tables
load('table_lambda_air.mat');
load('table_lambda_CaCO3.mat');

% call input_values and constants for calcutlation
con_struct_L_valve;


% CONVERSION OF VARIABLES
% temperatures


calc_values.T_CaCO3_in=convert_theta2T(input_values.theta_CaCO3_in);
calc_values.T_CaO_in=convert_theta2T(input_values.theta_CaO_in);

calc_values.T=calc_T(...
	calc_values.T_CaCO3_in,... 
	calc_values.T_CaO_in...
);

% cp values for T, CAUTION!! T_CaO >> T_CaCO3, mean value could be imprecise!!!!

calc_values.cp_air=calc_cp_air(calc_values.T);
calc_values.cp_CaCO3=calc_cp_CaCO3(calc_values.T);
calc_values.cp_CaO=calc_cp_CaO(calc_values.T);
calc_values.cp_CaCO3_mf=calc_cp_CaCO3_mf(input_values.m_frac_CaO, input_values.m_frac_CaCO3, calc_values.cp_CaO, calc_values.cp_CaCO3);


% lambda values for T
% load('table_lambda_air.mat');
% load('table_lambda_CaCO3.mat');
% load('table_lambda_hx_pipe.mat');

calc_values.lambda_air=lookup_lambda_air(calc_values.T, table_lambda_air);
calc_values.lambda_CaCO3=lookup_lambda_CaCO3(calc_values.T, table_lambda_CaCO3);
calc_values.lambda_CaO=lookup_lambda_CaCO3(calc_values.T, table_lambda_CaCO3);           % NOT YET AVAILABLE

% lambda concrete
calc_values.lambda_hx_pipe=lookup_lambda_hx_pipe(calc_values.T, table_lambda_hx_pipe);



%% lambda_bed for CaO

calc_values.lambda_bed=calc_heat_conductivity_bed(...
	calc_values.T, ...
	input_values.rho_p_CaO, ...
	input_values.rho_bed_CaO, ...
	input_values.C, ...
	constants.R, ...
	input_values.M, ...
    calc_values.lambda_CaO, ...
    calc_values.lambda_air, ...
	input_values.p, ...
    calc_values.cp_air, ...
	input_values.Cf,...
	input_values.f_zeta,...
	input_values.d_p, ...
	constants.sigma,...
	input_values.epsilon_bed,...
	input_values.phi_p...
);


[calc_values.alpha_CaO, calc_values.alpha_CaO_WS, calc_values.alpha_CaO_beddry, calc_values.alpha_CaO_WP]=calc_heat_transfer_coefficient(...
	calc_values.T,              ...
	input_values.C,             ...
	constants.R,                ...
	input_values.M,             ...
	calc_values.lambda_air,     ...
	input_values.p,             ...
	calc_values.cp_air,         ...
	input_values.rho_bed_CaO,     ...
	calc_values.lambda_bed,     ...
	calc_values.cp_CaO,       ...
	constants.sigma,            ...
	input_values.epsilon_w,     ...
	input_values.epsilon_bed,   ...
    input_values.d_p,           ...
    input_values.delta_p,       ...
    input_values.phi,           ...
	parameters.t_res              ...
);



%% lambda_bed for CaCO3
calc_values.lambda_bed=calc_heat_conductivity_bed(...
	calc_values.T, ...
	input_values.rho_p_CaCO3, ...
	input_values.rho_bed_CaCO3, ...
	input_values.C, ...
	constants.R, ...
	input_values.M, ...
    calc_values.lambda_CaCO3, ...
    calc_values.lambda_air, ...
	input_values.p, ...
    calc_values.cp_air, ...
	input_values.Cf,...
	input_values.f_zeta,...
	input_values.d_p, ...
	constants.sigma,...
	input_values.epsilon_bed,...
	input_values.phi_p...
);


[calc_values.alpha_CaCO3, calc_values.alpha_CaCO3_WS, calc_values.alpha_CaCO3_beddry, calc_values.alpha_CaCO3_WP]=calc_heat_transfer_coefficient(...
	calc_values.T,              ...
	input_values.C,             ...
	constants.R,                ...
	input_values.M,             ...
	calc_values.lambda_air,     ...
	input_values.p,             ...
	calc_values.cp_air,         ...
	input_values.rho_bed_CaCO3, ...
	calc_values.lambda_bed,     ...
	calc_values.cp_CaCO3_mf,       ...
	constants.sigma,            ...
	input_values.epsilon_w,     ...
	input_values.epsilon_bed,   ...
    input_values.d_p,           ...
    input_values.delta_p,       ...
    input_values.phi,           ...
	parameters.t_res              ...
);

% Heat Exchanger Parameter (here cylindric pipe wall)

 fprintf('ein L-Valve vs. mehrere L-Valves parallel, A_CaO_cs_tot bzw. A_CaCO3_cs_tot durch Anzahl L-Valve, neue calc_functions für A_CaO_cs_tot und implementieren in d_i_hx_pipe und  d_outer_pipe !! \n')

calc_values.d_i_hx_pipe=calc_d_i_hx_pipe(...
    parameters.w_CaO,...
    input_values.m_p_CaO,...
    input_values.rho_bed_CaO...
);

calc_values.d_outer_pipe=calc_d_outer_pipe(...
    parameters.w_CaCO3,...
    input_values.m_p_CaCO3,...
    input_values.rho_bed_CaCO3,...
    calc_values.d_i_hx_pipe,...
    input_values.th_hx_pipe...
);

calc_values.d_o_hx_pipe=calc_d_o_hx_pipe(...
    calc_values.d_i_hx_pipe,...
    input_values.th_hx_pipe...
);

calc_values.length_hx_pipe=calc_length_hx_pipe(...
    parameters.w_CaO,...
    parameters.t_res...
);


calc_values.A_o_hx_pipe=calc_A_o_hx_pipe(calc_values.length_hx_pipe, calc_values.d_o_hx_pipe);
calc_values.A_i_hx_pipe=calc_A_i_hx_pipe(calc_values.length_hx_pipe, calc_values.d_i_hx_pipe);
calc_values.A_m_hx_pipe=calc_A_m_hx_pipe(calc_values.A_i_hx_pipe, calc_values.A_o_hx_pipe);

% thermal transmittance

calc_values.k_hx_pipe=calc_k_hx_pipe(   ...
    calc_values.A_i_hx_pipe,			...
    calc_values.A_m_hx_pipe,			...
    calc_values.A_o_hx_pipe,			...
    calc_values.alpha_CaO,				...
    calc_values.alpha_CaCO3,			...
    calc_values.lambda_hx_pipe,			...
    input_values.th_hx_pipe				...
 );

% C_p heat capacity rate

calc_values.C_p_CaO = calc_C_p(input_values.m_p_CaO, calc_values.cp_CaO);
calc_values.C_p_CaCO3 = calc_C_p(input_values.m_p_CaCO3, calc_values.cp_CaCO3);

% outlet temperature

calc_values.T_CaO_out=calc_T_CaO_out_LV(...
    calc_values.T_CaO_in,...
    calc_values.T_CaCO3_in,...
    calc_values.C_p_CaO,...
    calc_values.C_p_CaCO3,...
    calc_values.A_m_hx_pipe,...
    calc_values.k_hx_pipe...
);

calc_values.T_CaCO3_out= calc_T_CaCO3_out_LV(...
    calc_values.T_CaO_in,...
    calc_values.T_CaCO3_in,...
    calc_values.C_p_CaO,...
    calc_values.C_p_CaCO3,...
    calc_values.A_m_hx_pipe,...
    calc_values.k_hx_pipe...
);

calc_values.theta_CaO_out=convert_T2theta(calc_values.T_CaO_out);
calc_values.theta_CaCO3_out=convert_T2theta(calc_values.T_CaCO3_out);


result=calc_values.theta_CaCO3_out;

%ANPASSEN

% critical residence time

% calc_values.t_c=calc_t_c(   ...
%     input_values.rho_p_bed, ...
%     calc_values.lambda_bed, ...
%     calc_values.cp_CaCO3,   ...
%     calc_values.alpha_WS    ...
% );

end
