% load('Test_plates_02.mat');
% load('table_lambda_air.mat');
% load('table_lambda_CaCO3.mat');


% Plate model with molten salt

%% Phase 1: Heat Transfer CaO to Plates

% CONVERSION OF VARIABLES
% temperatures
calc_values.T_plate_in_1=convert_theta2T(input_values.theta_plate_in_1);
calc_values.T_CaO_in_1=convert_theta2T(input_values.theta_CaO_in_1);

calc_values.T_m_1=calc_T(...
	calc_values.T_plate_in_1,... 
	calc_values.T_CaO_in_1...
);

% cp values for T

calc_values.cp_air_1=calc_cp_air(calc_values.T_m_1);
calc_values.cp_CaO_1=calc_cp_CaO(calc_values.T_m_1);

% lambda values for T

calc_values.lambda_air_1=lookup_lambda_air(calc_values.T_m_1, table_lambda_air);
calc_values.lambda_CaO_1=lookup_lambda_CaCO3(calc_values.T_m_1, table_lambda_CaCO3); % keine Werte für CaO, Annahme: lambda_CaO = lambda_CaCO3

% lambda_bed, only particles in bed, here CaCO3

calc_values.lambda_bed_1=calc_heat_conductivity_bed(...
	calc_values.T_m_1, ...
	input_values.rho_p_CaO, ...
	input_values.rho_p_bed_CaO, ...
	input_values.C, ...
	constants.R, ...
	input_values.M, ...
    calc_values.lambda_CaO_1, ...
    calc_values.lambda_air_1, ...
	input_values.p, ...
    calc_values.cp_air_1, ...
	input_values.Cf,...
	input_values.f_zeta,...
	input_values.d_p, ...
	constants.sigma,...
	input_values.epsilon_bed,...
	input_values.phi_p...
);


[calc_values.alpha_1, calc_values.alpha_WS_1, calc_values.alpha_beddry_1, calc_values.alpha_WP_1] =calc_heat_transfer_coefficient(...
	calc_values.T_m_1,              ...
	input_values.C,             ...
	constants.R,                ...
	input_values.M,             ...
	calc_values.lambda_air_1,      ...
	input_values.p,             ...
	calc_values.cp_air_1,          ...
	input_values.rho_p_CaO,     ...
	calc_values.lambda_CaO_1,    ...
	calc_values.cp_CaO_1,      ...
	constants.sigma,            ...
	input_values.epsilon_w,     ...
	input_values.epsilon_bed,   ...
    input_values.d_p,           ...
    input_values.delta_p,       ...
    input_values.phi,            ...
	input_values.t_1              ...
);

% Heat Exchanger Parameter (here plates with molten salt) same geometry for CaCO3 and CaO HX

calc_values.A_plate=calc_A_plate(input_values.height_plate, input_values.width_plate);
calc_values.A_plates_row=calc_A_plates_row(calc_values.A_plate, input_values.n_plates_row);
calc_values.A_plates_tot=calc_A_plates_tot(calc_values.A_plates_row, input_values.n_rows);


% heat flux

calc_values.q_p_1=calc_q_p_hx_CaO_plates(   ...
    calc_values.alpha_1,      ...
	calc_values.T_plate_in_1,   ...
	calc_values.T_CaO_in_1 ...
);


% outlet temperature

calc_values.T_CaO_out=calc_T_CaO_out_plates(...
    calc_values.T_CaO_in_1, 	...
    calc_values.T_plate_in_1, 	...
	calc_values.alpha_1, 		...
    calc_values.A_plates_tot, 	...
    input_values.m_CaO_1, 	...
    calc_values.cp_CaO_1 		...
);

% critical residence time

calc_values.t_c_1=calc_t_c(   ...
    input_values.rho_p_CaO, ...
    calc_values.lambda_bed_1, ...
    calc_values.cp_CaO_1,   ...
    calc_values.alpha_WS_1    ...
);


%% Phase 3: Heat Transfer Plates to CaCO3

% CONVERSION OF VARIABLES
% temperatures
calc_values.T_plate_in_3=convert_theta2T(input_values.theta_plate_in_3);
calc_values.T_CaCO3_in_3=convert_theta2T(input_values.theta_CaCO3_in_3);

calc_values.T_m_3=calc_T(...
	input_values.theta_CaCO3_in_3,... 
	input_values.theta_plate_in_3...
);

% cp values for T

calc_values.cp_air_3=calc_cp_air(calc_values.T_m_3);
calc_values.cp_CaCO3_3=calc_cp_CaCO3(calc_values.T_m_3);
calc_values.cp_CaO_3=calc_cp_CaO(calc_values.T_m_3);
calc_values.cp_CaCO3_mf_3=calc_cp_CaCO3_mf(input_values.m_frac_CaO_3, input_values.m_frac_CaCO3_3, calc_values.cp_CaO_3, calc_values.cp_CaCO3_3);

% lambda values for T
% load('table_lambda_air.mat');
% load('table_lambda_CaCO3.mat');

calc_values.lambda_air_3=lookup_lambda_air(calc_values.T_m_3, table_lambda_air);
calc_values.lambda_CaCO3_3=lookup_lambda_CaCO3(calc_values.T_m_3, table_lambda_CaCO3);


% lambda_bed, only particles in bed, here CaCO3

calc_values.lambda_bed_3=calc_heat_conductivity_bed(...
	calc_values.T_m_3, ...
	input_values.rho_p_CaCO3, ...
	input_values.rho_p_bed_CaCO3, ...
	input_values.C, ...
	constants.R, ...
	input_values.M, ...
    calc_values.lambda_CaCO3_3, ...
    calc_values.lambda_air_3, ...
	input_values.p, ...
    calc_values.cp_air_3, ...
	input_values.Cf,...
	input_values.f_zeta,...
	input_values.d_p, ...
	constants.sigma,...
	input_values.epsilon_bed,...
	input_values.phi_p...
);


[calc_values.alpha_3, calc_values.alpha_WS_3, calc_values.alpha_beddry_3, calc_values.alpha_WP_3] =calc_heat_transfer_coefficient(...
	calc_values.T_m_3,              ...
	input_values.C,             ...
	constants.R,                ...
	input_values.M,             ...
	calc_values.lambda_air_3,      ...
	input_values.p,             ...
	calc_values.cp_air_3,          ...
	input_values.rho_p_CaCO3,     ...
	calc_values.lambda_CaCO3_3,    ...
	calc_values.cp_CaCO3_mf_3,      ...
	constants.sigma,            ...
	input_values.epsilon_w,     ...
	input_values.epsilon_bed,   ...
    input_values.d_p,           ...
    input_values.delta_p,       ...
    input_values.phi,            ...
	input_values.t_3              ...
);

% Heat Exchanger Parameter (here plates with molten salt) same geometry for CaCO3 and CaO HX

calc_values.A_plate=calc_A_plate(input_values.height_plate, input_values.width_plate);
calc_values.A_plates_row=calc_A_plates_row(calc_values.A_plate, input_values.n_plates_row);
calc_values.A_plates_tot=calc_A_plates_tot(calc_values.A_plates_row, input_values.n_rows);


% heat flow

calc_values.q_p_3=calc_q_p_hx_CaCO3_plates(   ...
    calc_values.alpha_3,        ...
	calc_values.T_plate_in_3,   ...
	calc_values.T_CaCO3_in_3    ...
);


% outlet temperature

calc_values.T_CaCO3_out=calc_T_CaCO3_out_plates(...
    calc_values.T_CaCO3_in_3, 	...
    calc_values.T_plate_in_3, 	...
	calc_values.alpha_3, 		...
    calc_values.A_plates_tot, 	...
    input_values.m_CaCO3_3, 	...
    calc_values.cp_CaCO3_mf_3 		...
);

% critical residence time

calc_values.t_c_3=calc_t_c(   ...
    input_values.rho_p_CaCO3, ...
    calc_values.lambda_bed_3, ...
    calc_values.cp_CaCO3_mf_3,   ...
    calc_values.alpha_WS_3    ...
);


